version: "3.9"

services:
  ewm-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:15
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
